apiVersion: v1
kind: ConfigMap
metadata:
  name: id-server-production-config
data:
  PROFILE: production
  PUBLIC_EARTH_NHHOS_URL: http://desk-ip.nhsoft.cn:8099/
  auth.url: https://mercury-node-center.nhsoft.cn
  profiles: production
  sms.appid: venzs999999
  sms.secret: a274f1e5e3ag2as1dg2rgRew48f5a4
  sms.url: https://sms-center.nhsoft.cn/sms-center/sms/merchants/send_message_by_template
  spring.datasource.password: wJ7o%,1Z=_F#J5N
  spring.datasource.url: jdbc:mysql://10.16.9.192:3306/id_server?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
  spring.datasource.username: shenyu
  spring.redis.host: redis-9fa8537a-65e8-4005-af9d-285313e7efae.cn-east-3.dcs.myhuaweicloud.com
  spring.redis.password: CFCoD2UCDE5Ws1z
  token.company-ids: '''60506,99605'''
  token.login-type: '''3'''
  weixin.appid: wx3f599bd6f924d97e
  weixin.secret: 5c4909cd36b6e3717eecb7a6c2693e4a
