apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
  name: xxljobadminnew
  namespace: xxl-job
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: xxljobadminnew
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
      labels:
        app: xxljobadminnew
        version: v1
    spec:
      containers:
      - env:
        - name: PAAS_APP_NAME
          value: xxljobadminnew
        - name: PAAS_NAMESPACE
          value: xxl-job
        - name: PAAS_PROJECT_ID
          value: 0cca93a109800f442ffec00cba0f5e6f
        envFrom:
        - configMapRef:
            name: xxl-job-admin-config
        image: swr.cn-east-3.myhuaweicloud.com/lemon-develop/xxljob_admin:v20240116213241
        imagePullPolicy: Always
        name: xxljobadminnew
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /xxl-job-admin/echo
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "2"
            memory: 768Mi
          requests:
            cpu: "2"
            memory: 768Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: default-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
