apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
  name: amazoncenter-task
  namespace: xxl-job
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: amazoncenter-task
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        redeploy-timestamp: "1706155113058"
      creationTimestamp: null
      labels:
        app: amazoncenter-task
        version: v1
    spec:
      containers:
      - env:
        - name: PAAS_APP_NAME
          value: amazoncenter-task
        - name: PAAS_NAMESPACE
          value: xxl-job
        - name: PAAS_PROJECT_ID
          value: 0cca93a109800f442ffec00cba0f5e6f
        - name: JDBC_BOOKCODE
          value: '{8012.8013}'
        - name: REDIS_HOST
          value: 47.111.99.207
        - name: REDIS_PASS
          value: d52cKyUm9jgbdie3YW4e
        - name: CAL_GROUP_CUSTOMER
          value: "true"
        - name: POS_ORDER_FETCH_SIZE
          value: "200"
        - name: POS_ORDER_BATCH_SIZE
          value: "25"
        - name: ENV
          value: local
        - name: XXL_JOB_ADMIN_ADDRESSES
          value: http://xxljob-admin-dev.xxl-job.svc.cluster.local:8080/xxl-job-admin
        - name: NHHOS_URL
          value: http://csp.nhsoft.cn/ServiceDesk/
        - name: XXL_JOB_USER_NAME
          value: lemeng365
        - name: XXL_JOB_USER_PASSWORD
          value: "123456"
        - name: XXL_JOB_ACCESS_TOKEN
          value: "20231116"
        - name: APP_NAME
          value: AMA
        - name: PUBLIC_ENVIRONMENT
          value: SHARA
        - name: XXL_JOB_GROUP_VERSION
          value: v1.0
        - name: DBSOURCE_NAMES
          value: AMA1,MYSQL
        image: swr.cn-east-3.myhuaweicloud.com/lemon-develop/amazon-center-task:v202401101520-tn
        imagePullPolicy: Always
        name: amazoncenter-task
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /amazonCenterTask/echo
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: default-secret
      restartPolicy: Always
      schedulerName: default-scheduler
