apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
  name: minipay-daemon-test
  namespace: hwtest-node-dx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minipay-daemon-test
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
      labels:
        app: minipay-daemon-test
        version: v1
    spec:
      containers:
      - env:
        - name: PAAS_APP_NAME
          value: minipay-daemon-test
        - name: PAAS_NAMESPACE
          value: hwtest-node-dx
        - name: PAAS_PROJECT_ID
          value: 0cca93a109800f442ffec00cba0f5e6f
        - name: PROFILE
          value: test
        envFrom:
        - configMapRef:
            name: hwtest-minipay-daemon-config
        image: swr.cn-east-3.myhuaweicloud.com/lemon-develop/minipay-daemon-boot:v20240115155002
        imagePullPolicy: IfNotPresent
        name: minipay-daemon-test
        resources:
          limits:
            memory: 2Gi
          requests:
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: default-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
