apiVersion: apps/v1
kind: Deployment
metadata:
  name: xxl-job-admin
  namespace: xxl-job
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: xxl-job-admin
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        redeploy-timestamp: "1704935508665"
      creationTimestamp: null
      labels:
        app: xxl-job-admin
        version: v1
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: xxl-job-admin
        image: swr.cn-east-3.myhuaweicloud.com/lemon-develop/xxljob_admin:v20240110215418
        imagePullPolicy: IfNotPresent
        name: xxl-job-admin
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /xxl-job-admin/echo
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "2"
            memory: 768Mi
          requests:
            cpu: "2"
            memory: 768Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: default-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 300
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 300
